[package]
name = "iggy-py"
version = "0.2.3"
edition = "2021"
authors = ["Dario Lencina Talarico <darioalessandrolencina@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "iggy_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
iggy = "0.5.0"
tokio = { version = "1", features = ["full"] }
bytes = "1.5"
openssl = { version = "0.10.*", features = ["vendored"] }
